# Form implementation generated from reading ui file 'DEMto3D_Dialog/SelectLayer_dialog_base.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SelectLayer_dialog_base(object):
    def setupUi(self, SelectLayer_dialog_base):
        SelectLayer_dialog_base.setObjectName("SelectLayer_dialog_base")
        SelectLayer_dialog_base.resize(227, 86)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/DEMto3D/icons/demto3d.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        SelectLayer_dialog_base.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(SelectLayer_dialog_base)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=SelectLayer_dialog_base)
        self.label.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.mMapLayerComboBox = QgsMapLayerComboBox(parent=SelectLayer_dialog_base)
        self.mMapLayerComboBox.setObjectName("mMapLayerComboBox")
        self.verticalLayout.addWidget(self.mMapLayerComboBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=SelectLayer_dialog_base)
        self.buttonBox.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SelectLayer_dialog_base)
        self.buttonBox.accepted.connect(SelectLayer_dialog_base.accept) # type: ignore
        self.buttonBox.rejected.connect(SelectLayer_dialog_base.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SelectLayer_dialog_base)
        SelectLayer_dialog_base.setTabOrder(self.label, self.mMapLayerComboBox)
        SelectLayer_dialog_base.setTabOrder(self.mMapLayerComboBox, self.buttonBox)

    def retranslateUi(self, SelectLayer_dialog_base):
        _translate = QtCore.QCoreApplication.translate
        SelectLayer_dialog_base.setWindowTitle(_translate("SelectLayer_dialog_base", "Layer extent"))
        self.label.setText(_translate("SelectLayer_dialog_base", "Select a layer:"))
from qgsmaplayercombobox import QgsMapLayerComboBox
