# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DEMto3D_dialog_base.ui'
#
# Created: Fri Aug 28 12:01:42 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DEMto3DDialogBase(object):
    def setupUi(self, DEMto3DDialogBase):
        DEMto3DDialogBase.setObjectName(_fromUtf8("DEMto3DDialogBase"))
        DEMto3DDialogBase.setWindowModality(QtCore.Qt.WindowModal)
        DEMto3DDialogBase.resize(471, 550)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/DEMto3D/icons/demto3d.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DEMto3DDialogBase.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(DEMto3DDialogBase)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(DEMto3DDialogBase)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 53))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 53))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.LayerComboBox = QtGui.QComboBox(self.groupBox)
        self.LayerComboBox.setObjectName(_fromUtf8("LayerComboBox"))
        self.verticalLayout_2.addWidget(self.LayerComboBox)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(DEMto3DDialogBase)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 118))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 118))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setMinimumSize(QtCore.QSize(0, 25))
        self.label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/DEMto3D/icons/upleft.png")))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.XMinLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.XMinLineEdit.setObjectName(_fromUtf8("XMinLineEdit"))
        self.gridLayout.addWidget(self.XMinLineEdit, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.YMaxLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.YMaxLineEdit.setObjectName(_fromUtf8("YMaxLineEdit"))
        self.gridLayout.addWidget(self.YMaxLineEdit, 0, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/DEMto3D/icons/downright.png")))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 1, 1, 1, 1)
        self.XMaxLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.XMaxLineEdit.setObjectName(_fromUtf8("XMaxLineEdit"))
        self.gridLayout.addWidget(self.XMaxLineEdit, 1, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 3, 1, 1)
        self.YMinLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.YMinLineEdit.setObjectName(_fromUtf8("YMinLineEdit"))
        self.gridLayout.addWidget(self.YMinLineEdit, 1, 4, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(330, -1, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.FullExtToolButton = QtGui.QToolButton(self.groupBox_2)
        self.FullExtToolButton.setMinimumSize(QtCore.QSize(20, 20))
        self.FullExtToolButton.setMaximumSize(QtCore.QSize(20, 20))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/DEMto3D/icons/full_extension.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FullExtToolButton.setIcon(icon1)
        self.FullExtToolButton.setObjectName(_fromUtf8("FullExtToolButton"))
        self.horizontalLayout.addWidget(self.FullExtToolButton)
        self.LayerExtToolButton = QtGui.QToolButton(self.groupBox_2)
        self.LayerExtToolButton.setMinimumSize(QtCore.QSize(20, 20))
        self.LayerExtToolButton.setMaximumSize(QtCore.QSize(20, 20))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/DEMto3D/icons/layer_extension.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LayerExtToolButton.setIcon(icon2)
        self.LayerExtToolButton.setObjectName(_fromUtf8("LayerExtToolButton"))
        self.horizontalLayout.addWidget(self.LayerExtToolButton)
        self.CustomExtToolButton = QtGui.QToolButton(self.groupBox_2)
        self.CustomExtToolButton.setMinimumSize(QtCore.QSize(20, 20))
        self.CustomExtToolButton.setMaximumSize(QtCore.QSize(20, 20))
        self.CustomExtToolButton.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/DEMto3D/icons/cursor_extension.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CustomExtToolButton.setIcon(icon3)
        self.CustomExtToolButton.setObjectName(_fromUtf8("CustomExtToolButton"))
        self.horizontalLayout.addWidget(self.CustomExtToolButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(DEMto3DDialogBase)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setContentsMargins(15, -1, -1, -1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setMinimumSize(QtCore.QSize(100, 20))
        self.label_9.setMaximumSize(QtCore.QSize(108, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_3.addWidget(self.label_9)
        self.SpacingLineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.SpacingLineEdit.setMinimumSize(QtCore.QSize(75, 20))
        self.SpacingLineEdit.setMaximumSize(QtCore.QSize(75, 20))
        self.SpacingLineEdit.setObjectName(_fromUtf8("SpacingLineEdit"))
        self.horizontalLayout_3.addWidget(self.SpacingLineEdit)
        self.label18 = QtGui.QLabel(self.groupBox_3)
        self.label18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label18.setObjectName(_fromUtf8("label18"))
        self.horizontalLayout_3.addWidget(self.label18)
        self.RecomSpacinglabel = QtGui.QLabel(self.groupBox_3)
        self.RecomSpacinglabel.setObjectName(_fromUtf8("RecomSpacinglabel"))
        self.horizontalLayout_3.addWidget(self.RecomSpacinglabel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, 9, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setMinimumSize(QtCore.QSize(100, 20))
        self.label_11.setMaximumSize(QtCore.QSize(100, 20))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_4.addWidget(self.label_11)
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_4.addWidget(self.label_12)
        self.HeightLineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.HeightLineEdit.setObjectName(_fromUtf8("HeightLineEdit"))
        self.horizontalLayout_4.addWidget(self.HeightLineEdit)
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_4.addWidget(self.label_13)
        self.WidthLineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.WidthLineEdit.setObjectName(_fromUtf8("WidthLineEdit"))
        self.horizontalLayout_4.addWidget(self.WidthLineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, 230, -1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_15 = QtGui.QLabel(self.groupBox_3)
        self.label_15.setMinimumSize(QtCore.QSize(82, 20))
        self.label_15.setMaximumSize(QtCore.QSize(82, 20))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_5.addWidget(self.label_15)
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setMinimumSize(QtCore.QSize(12, 20))
        self.label_14.setMaximumSize(QtCore.QSize(20, 20))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_5.addWidget(self.label_14)
        self.ScaleLineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.ScaleLineEdit.setMinimumSize(QtCore.QSize(90, 20))
        self.ScaleLineEdit.setMaximumSize(QtCore.QSize(90, 20))
        self.ScaleLineEdit.setObjectName(_fromUtf8("ScaleLineEdit"))
        self.horizontalLayout_5.addWidget(self.ScaleLineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(DEMto3DDialogBase)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 53))
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 53))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_6.setContentsMargins(15, -1, -1, -1)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_16 = QtGui.QLabel(self.groupBox_4)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_6.addWidget(self.label_16)
        self.ZScaleDoubleSpinBox = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.ZScaleDoubleSpinBox.setDecimals(1)
        self.ZScaleDoubleSpinBox.setMaximum(10.0)
        self.ZScaleDoubleSpinBox.setSingleStep(0.5)
        self.ZScaleDoubleSpinBox.setProperty("value", 1.0)
        self.ZScaleDoubleSpinBox.setObjectName(_fromUtf8("ZScaleDoubleSpinBox"))
        self.horizontalLayout_6.addWidget(self.ZScaleDoubleSpinBox)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_5 = QtGui.QGroupBox(DEMto3DDialogBase)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 81))
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 81))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.BaseHeightLineEdit = QtGui.QLineEdit(self.groupBox_5)
        self.BaseHeightLineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.BaseHeightLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.BaseHeightLineEdit.setObjectName(_fromUtf8("BaseHeightLineEdit"))
        self.gridLayout_2.addWidget(self.BaseHeightLineEdit, 0, 1, 1, 1)
        self.ZMinLabel = QtGui.QLabel(self.groupBox_5)
        self.ZMinLabel.setMinimumSize(QtCore.QSize(65, 20))
        self.ZMinLabel.setMaximumSize(QtCore.QSize(56, 20))
        self.ZMinLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ZMinLabel.setObjectName(_fromUtf8("ZMinLabel"))
        self.gridLayout_2.addWidget(self.ZMinLabel, 0, 3, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_5)
        self.label_17.setMinimumSize(QtCore.QSize(55, 0))
        self.label_17.setMaximumSize(QtCore.QSize(55, 16777215))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 0, 0, 1, 1)
        self.ZMaxLabel = QtGui.QLabel(self.groupBox_5)
        self.ZMaxLabel.setMinimumSize(QtCore.QSize(65, 20))
        self.ZMaxLabel.setMaximumSize(QtCore.QSize(65, 20))
        self.ZMaxLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ZMaxLabel.setObjectName(_fromUtf8("ZMaxLabel"))
        self.gridLayout_2.addWidget(self.ZMaxLabel, 1, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 0, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_5)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 1, 2, 1, 1)
        self.HeightModelLabel = QtGui.QLabel(self.groupBox_5)
        self.HeightModelLabel.setObjectName(_fromUtf8("HeightModelLabel"))
        self.gridLayout_2.addWidget(self.HeightModelLabel, 1, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox_5)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 1, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.groupBox_6 = QtGui.QGroupBox(DEMto3DDialogBase)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 53))
        self.groupBox_6.setMaximumSize(QtCore.QSize(16777215, 53))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_6)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.RevereseZCheckBox = QtGui.QCheckBox(self.groupBox_6)
        self.RevereseZCheckBox.setMinimumSize(QtCore.QSize(0, 20))
        self.RevereseZCheckBox.setMaximumSize(QtCore.QSize(16777215, 20))
        self.RevereseZCheckBox.setObjectName(_fromUtf8("RevereseZCheckBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.RevereseZCheckBox)
        self.verticalLayout.addWidget(self.groupBox_6)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(220, -1, -1, -1)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.STLToolButton = QtGui.QToolButton(DEMto3DDialogBase)
        self.STLToolButton.setMinimumSize(QtCore.QSize(100, 25))
        self.STLToolButton.setMaximumSize(QtCore.QSize(100, 25))
        self.STLToolButton.setObjectName(_fromUtf8("STLToolButton"))
        self.horizontalLayout_9.addWidget(self.STLToolButton)
        self.CancelToolButton = QtGui.QToolButton(DEMto3DDialogBase)
        self.CancelToolButton.setMinimumSize(QtCore.QSize(100, 25))
        self.CancelToolButton.setMaximumSize(QtCore.QSize(100, 25))
        self.CancelToolButton.setObjectName(_fromUtf8("CancelToolButton"))
        self.horizontalLayout_9.addWidget(self.CancelToolButton)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.label_2.setBuddy(self.XMinLineEdit)
        self.label_3.setBuddy(self.YMaxLineEdit)
        self.label_5.setBuddy(self.XMaxLineEdit)
        self.label_6.setBuddy(self.YMinLineEdit)
        self.label_9.setBuddy(self.SpacingLineEdit)
        self.label_12.setBuddy(self.HeightLineEdit)
        self.label_13.setBuddy(self.WidthLineEdit)
        self.label_15.setBuddy(self.ScaleLineEdit)
        self.label_16.setBuddy(self.ZScaleDoubleSpinBox)
        self.label_17.setBuddy(self.BaseHeightLineEdit)

        self.retranslateUi(DEMto3DDialogBase)
        QtCore.QMetaObject.connectSlotsByName(DEMto3DDialogBase)
        DEMto3DDialogBase.setTabOrder(self.CancelToolButton, self.STLToolButton)
        DEMto3DDialogBase.setTabOrder(self.STLToolButton, self.LayerComboBox)
        DEMto3DDialogBase.setTabOrder(self.LayerComboBox, self.XMinLineEdit)
        DEMto3DDialogBase.setTabOrder(self.XMinLineEdit, self.YMaxLineEdit)
        DEMto3DDialogBase.setTabOrder(self.YMaxLineEdit, self.XMaxLineEdit)
        DEMto3DDialogBase.setTabOrder(self.XMaxLineEdit, self.YMinLineEdit)
        DEMto3DDialogBase.setTabOrder(self.YMinLineEdit, self.FullExtToolButton)
        DEMto3DDialogBase.setTabOrder(self.FullExtToolButton, self.LayerExtToolButton)
        DEMto3DDialogBase.setTabOrder(self.LayerExtToolButton, self.CustomExtToolButton)
        DEMto3DDialogBase.setTabOrder(self.CustomExtToolButton, self.SpacingLineEdit)
        DEMto3DDialogBase.setTabOrder(self.SpacingLineEdit, self.HeightLineEdit)
        DEMto3DDialogBase.setTabOrder(self.HeightLineEdit, self.WidthLineEdit)
        DEMto3DDialogBase.setTabOrder(self.WidthLineEdit, self.ScaleLineEdit)
        DEMto3DDialogBase.setTabOrder(self.ScaleLineEdit, self.ZScaleDoubleSpinBox)
        DEMto3DDialogBase.setTabOrder(self.ZScaleDoubleSpinBox, self.BaseHeightLineEdit)
        DEMto3DDialogBase.setTabOrder(self.BaseHeightLineEdit, self.RevereseZCheckBox)

    def retranslateUi(self, DEMto3DDialogBase):
        DEMto3DDialogBase.setWindowTitle(_translate("DEMto3DDialogBase", "DEM 3D printing", None))
        self.groupBox.setTitle(_translate("DEMto3DDialogBase", "Layer to print", None))
        self.groupBox_2.setTitle(_translate("DEMto3DDialogBase", "Print extent", None))
        self.label_2.setText(_translate("DEMto3DDialogBase", "X:", None))
        self.label_3.setText(_translate("DEMto3DDialogBase", "Y:", None))
        self.label_5.setText(_translate("DEMto3DDialogBase", "X:", None))
        self.label_6.setText(_translate("DEMto3DDialogBase", "Y:", None))
        self.FullExtToolButton.setToolTip(_translate("DEMto3DDialogBase", "Select full extent", None))
        self.FullExtToolButton.setStatusTip(_translate("DEMto3DDialogBase", "Select full extent", None))
        self.FullExtToolButton.setWhatsThis(_translate("DEMto3DDialogBase", "Select full extent", None))
        self.FullExtToolButton.setAccessibleName(_translate("DEMto3DDialogBase", "Select full extent", None))
        self.LayerExtToolButton.setToolTip(_translate("DEMto3DDialogBase", "Select layer extent", None))
        self.LayerExtToolButton.setStatusTip(_translate("DEMto3DDialogBase", "Select layer extent", None))
        self.LayerExtToolButton.setWhatsThis(_translate("DEMto3DDialogBase", "Select layer extent", None))
        self.LayerExtToolButton.setAccessibleName(_translate("DEMto3DDialogBase", "Select layer extent", None))
        self.CustomExtToolButton.setToolTip(_translate("DEMto3DDialogBase", "Draw extent", None))
        self.CustomExtToolButton.setStatusTip(_translate("DEMto3DDialogBase", "Draw extent", None))
        self.CustomExtToolButton.setWhatsThis(_translate("DEMto3DDialogBase", "Draw extent", None))
        self.CustomExtToolButton.setAccessibleName(_translate("DEMto3DDialogBase", "Draw extent", None))
        self.groupBox_3.setTitle(_translate("DEMto3DDialogBase", "Model size", None))
        self.label_9.setText(_translate("DEMto3DDialogBase", "Spacing (mm):", None))
        self.label18.setText(_translate("DEMto3DDialogBase", "Minimum recommended", None))
        self.RecomSpacinglabel.setText(_translate("DEMto3DDialogBase", "0.2 mm", None))
        self.label_11.setText(_translate("DEMto3DDialogBase", "Size:", None))
        self.label_12.setText(_translate("DEMto3DDialogBase", "Height (mm):", None))
        self.label_13.setText(_translate("DEMto3DDialogBase", "Width (mm):", None))
        self.label_15.setText(_translate("DEMto3DDialogBase", "Scale:", None))
        self.label_14.setText(_translate("DEMto3DDialogBase", "1:", None))
        self.groupBox_4.setTitle(_translate("DEMto3DDialogBase", "Exaggeration terrain", None))
        self.label_16.setText(_translate("DEMto3DDialogBase", "Exaggeration factor:", None))
        self.groupBox_5.setTitle(_translate("DEMto3DDialogBase", "Height base", None))
        self.ZMinLabel.setText(_translate("DEMto3DDialogBase", "0 m", None))
        self.label_17.setText(_translate("DEMto3DDialogBase", "Height (m):", None))
        self.ZMaxLabel.setText(_translate("DEMto3DDialogBase", "0 m", None))
        self.label_8.setText(_translate("DEMto3DDialogBase", "Lowest point:", None))
        self.label_10.setText(_translate("DEMto3DDialogBase", "Highest point:", None))
        self.HeightModelLabel.setText(_translate("DEMto3DDialogBase", "0 mm", None))
        self.label_21.setText(_translate("DEMto3DDialogBase", "Model height:", None))
        self.groupBox_6.setTitle(_translate("DEMto3DDialogBase", "Other parameters", None))
        self.RevereseZCheckBox.setText(_translate("DEMto3DDialogBase", "Terrain inversion", None))
        self.STLToolButton.setText(_translate("DEMto3DDialogBase", "Export to STL", None))
        self.CancelToolButton.setText(_translate("DEMto3DDialogBase", "Cancel", None))

from .. import resources_rc
